import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Navbar } from "@/components/navbar";
import { HomePhotos } from "@/components/homephotos";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Layla Sadeghi Namaghi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
        />
      </Head>

      <Navbar />

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}></div>

        <div className={styles.container}>
          <div className={styles.center}>
            <h1 className={styles.title}>Layla Sadeghi Namaghi</h1>
            <p className={styles.bio}>
              PhD in Computational Mathematics with a strong background in
              algorithm optimisation, advanced computational techniques, and
              mathematical modelling using MATLAB and Python. Eager to apply my
              programming and analytical expertise to a technical role where I
              can leverage these skills to drive innovation and business growth.
              Enthusiatic about science communication and effective
              collaboration. Keen programmer with additional experience in
              JavaScript, React, SQL.
            </p>
          </div>

          < HomePhotos />
  
        </div>
      </main>
    </>
  );
}
