import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] }); // for choosing font

export default function Home() {
  return (
    <>
      <Head>
        <title>Layla Sadeghi Namaghi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}></div>
        {/* Change `class` to `className` */}
        <div className="container">
          <div className={styles.center}>
            <p>Layla Sadeghi Namaghi</p>
          </div>

          <div className={styles.photoGrid}>
            <div className={styles.photoTile}>
              <Image src="/photos/3mt.jpg" alt="Photo 1" />
            </div>
            <div className={styles.photoTile}>
              <Image src="/photos/bake.jpg" alt="Photo 2" />
            </div>
            <div className={styles.photoTile}>
              <Image src="/photos/hannahfry.jpg" alt="Photo 3" />
            </div>
            <div className={styles.photoTile}>
              <Image src="/photos/icms.jpg" alt="Photo 4" />
            </div>
            <div className={styles.photoTile}>
              <Image src="/photos/outreach1.jpg" alt="Photo 5" />
            </div>
            <div className={styles.photoTile}>
              <Image src="/photos/talk1.jpg" alt="Photo 6" />
            </div>
            <div className={styles.photoTile}>
              <Image src="/photos/outreach2.jpg" alt="Photo 7" />
            </div>
            <div className={styles.photoTile}>
              <Image src="/photos/outreachcrypto.jpg" alt="Photo 8" />
            </div>
            <div className={styles.photoTile}>
              <Image src="/photos/photo9.jpg" alt="Photo 9" />
            </div>
          </div>
        </div>  
      </main>
    </>
  );
}
